### ISSUE TITLE
Allow to define a position for opening (morning) and closing (evening) by seasons

### ISSUE THREAD

**Issue by mguyard** [mguyard/appdaemon-coversmanager#55]
### Is your feature request related to a problem? Please describe.

N/A

### Describe the solution you'd like

Allow new parameters :

```
config:
  common:
    opening:
      position: 
        default: X
        seasons:
          spring: X
          summer: X
          autumn: X
          winter: X
    closing:
      position: 
        default: X
        seasons:
          spring: X
          summer: X
          autumn: X
          winter: X
```

config.common.[opening|closing].position.default is the defaut value (default to 100) and config.common.[opening|closing].position.[seasons] is optional and override config.common.[opening|closing].position.default.
If seasons parameters are defined, config.common.seasons is required.

To look if we can accept an integer but also a entity (sensor)

config.covers.[cover].positional. action need to be True if config.common.[opening|closing].position and config.common.[opening|closing].[seasons] is configured

Opening and closing process need to be adapt to use these parameters

### Describe alternatives you've considered

N/A

### Additional context

https://forum.hacf.fr/t/coversmanager-piloter-vos-volets-automatiquement-dapres-le-soleil/42673/32

### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/mguyard/appdaemon-coversmanager/labels/%F0%9F%9A%80%20feature-request).
